# las.ini configuration for geospatial dm
[project]
las.project.dir=""
las.meta.dir=""
las.product.dir=""

[header]
z_max=true
z_min=true
point_count=true
point_format=true
major_version=true
minor_version=true
creation_date=true
file_source_id=true

[exclude]
are_points_compressed=true
evlrs=true
extra_header_bytes=true
extra_vlr_bytes=true
file_source_id=true
generating_software=true
global_encoding=true
grow=true
max_point_count=true
maxs=true
mins=true
number_of_evlrs=true
number_of_points_by_return=true
offset_to_point_data=true
offsets=true
parse_crs=true
partial_reset=true
read_evlrs=true
read_from=true
remove_extra_dim=true
remove_extra_dims=true
scales=true
set_compressed=true
set_version_and_point_format=true
start_of_first_evlr=true
start_of_waveform_data_packet_record=true
system_identifier=true
update=true
uuid=true
version=true
vlrs=true
write_to=true
x_max=true
x_min=true
x_offset=true
x_scale=true
y_max=true
y_min=true
y_offset=true
y_scale=true
z_max=true
z_min=true
z_offset=true
z_scale=true
